### ISSUE TITLE
Make compatible with latest sanctuary-def (0.9.0)

### ISSUE THREAD

**Issue by jonahx** [JAForbes/sum-type#1]
At least, I believe this is the issue...

To reproduce, try this code:

```
const RangeError = SumType.Named('RangeError', {
  InvalidMin: [S.Any],
  InvalidMax: [S.Any],
  MinGreaterThanMax:  {min: Number, max: Number}
});
```
and you should see this error:

```
TypeError: Invalid values

The argument to ‘RecordType’ must be an object mapping field name to type.

The following mappings are invalid:

  - "0": Any

    at Object.RecordType (/Users/jg/Dropbox/node/messaging/messaging-types/node_modules/sum-type/node_modules/sanctuary-def/index.js:1527:13)
```

sum-type's current dependency is listed as sanctuary-def `^0.7.0`.  I tried uprading it just to see if it would work but I got a different error when installing sanctuary-def `0.9.0`:

```
TypeError: Invalid value

NullaryType :: String -> String -> (Any -> Boolean) -> Type
                         ^^^^^^
                           1

1)  function (a) { return a && a['@@type'] == typeName; } :: Function

The value at position 1 is not a member of ‘String’.
```

**Comment by davidchambers** [comment]
You should change `S.Any` to `$.Any` to avoid confusion, @jonahx. `S` is typically used to refer to `sanctuary` whereas `$` is typically used to refer to `sanctuary-def`.

This issue is related to sanctuary-js/sanctuary#327, I believe. Ideally `sum-type` would specify the version of `sanctuary-def` with which it is compatible.

**Comment by jonahx** [comment]
@davidchambers ok thanks for the tip about `$`.  re: the issue here, you are saying that the correct solution is to add sanctuary-def as a peer dependency?

**Comment by davidchambers** [comment]
> you are saying that the correct solution is to add sanctuary-def as a peer dependency?

I *think* so, but I haven't used peer dependencies in the past and I haven't yet spent time convincing myself that they address this issue.

**Comment by jonahx** [comment]
@davidchambers In the meantime it looks like I can fix my problem by using `T` instead of `$.Any`.  I'm guessing the breaking change had something to do with how `@@type` goes in the type representative, and the old version is not recognizing that `Any` is in fact the type `Any` because of that?

**Comment by davidchambers** [comment]
I believe your understanding to be correct, Jonah. It's important to be clear that the solution to this problem is not to update this project's `sanctuary-def` dependency (we should do so anyway), but to find some mechanism—likely peer dependencies—to prevent this package from being used with a version of `sanctuary-def` other than that on which it depends.

**Comment by JAForbes** [comment]
@davidchambers @jonahx I'll push an update now that updates the library to depend on 0.9, and also mark sanctuary-def as a peer dep.

**Comment by JAForbes** [comment]
New release now has a peer dep on 0.9.0 and the dependency is parameterized.

https://github.com/JAForbes/sum-type/releases/tag/v0.7.0

**Comment by JAForbes** [comment]
@davidchambers I've also updated `{check: Boolean, ...}` to be `{ checkTypes: Boolean, ...}` to match sanctuary's signature instead of union-type's.

**Comment by jonahx** [comment]
@JAForbes Thanks for quick fix!

**Comment by davidchambers** [comment]
It looks as though you forgot to push to `master`, @JAForbes.

Would you like me to submit a pull request to integrate [xyz][1] so you can run `npm run release minor` in future?


[1]: https://github.com/davidchambers/xyz
