### ISSUE TITLE
Generate type constructors automatically.

### ISSUE THREAD

**Issue by JAForbes** [JAForbes/sum-type#11]
Generate Binary/Unary/NAry(?) type constructors automatically for each case of the union.

**Comment by davidchambers** [comment]
It would be a single type constructor for the type, not one per data constructor.

```haskell
data Maybe a = Nothing | Just a
```

Maybe is a unary type, as we can see by the type parameter `a` to the left of the `=`.

```haskell
data Either a b = Left a | Right b
```

Either is a binary type, as we can see from the type parameters `a` and `b`.

With sum-type we only specify the stuff to the right of the `=`, so it's not clear how to determine the arity of the type and the order of the type arguments. One option is to rely on alphabetical ordering of type variables:

```json
{"Nothing": [], "Just": ["a"]}
```

```json
{"Left": ["a"], "Right": ["b"]}
```

**Comment by JAForbes** [comment]
@davidchambers Great clarification.

Alphabetical could work.  Could we use a count of type variables and order of appearance as well?  Or would that introduce problems.

To elaborate.

```
const a = $.TypeVariable('a')
const b = $.TypeVariable('b')

const Either = Type.Named('Either', { Left: { a }, Right: { b } })
```

Would automatically detect there's two type variables: a and b, and they are ordered by appearance: a first then b.

So the type constructor can be generated automatically as `BinaryType('Either', {}, [a, b], test([], Either))`

I'm relying on ordering of Object.keys which until es6 was problematic theoretically, but [no longer](http://2ality.com/2015/10/property-traversal-order-es6.html).

I'm considering moving away from list syntax and spreading in `case` because in practice it leads to brittle code ( #4 #3 #6 ) 

I think we can use sanctuary-def type variables directly, instead of inferring it.

Perhaps for convenience sum-type could provide access to $.TypeVariable, as `Type.var` or something (or could even just have `a`,`b`,`c` as an export by default for the common case.  But I think being explicit initially would be fine for a release.

Do you think that would work?

**Comment by davidchambers** [comment]
Relying on alphabetical ordering of type variables seems less magical to me than relying on object enumeration order, but I think either approach would work. :)

**Comment by JAForbes** [comment]
Yeah I agree its more magical, but at the same time I think it's less surprising.

In Haskell, couldn't I technically define types like:

```
data Either b a = Right b | Left a
```

Where variables appear in non-alphabetical order (not sure at all if that's true).

Its probably strange, and non-conventional.  But let's say, someone did the same in js:

```
const Either = Type.Named( 'Either', {
  Right: { b }
  ,Left: { a }
})
```

I think it'd be surprising for the generated constructor to order the type variables as `a b` when they appeared as `b a`, and it'd be odd to render it as `Left a | Right b` when it was declared as `{ Right { b }, Left { a } }`

Behind the scenes, it seems convoluted, but it seems to mimic more closely, the Haskell syntax.

That said, I have never written a line of Haskell 💣 , so maybe it doesn't work that way at all.

**Comment by davidchambers** [comment]
In the Haskell example, it's the `Either a b` that specifies order rather than the `Left a | Right b`. With sum-type there's currently no equivalent of the left-hand side of the `data` declaration.

I would be surprised to discover that these expressions are not equivalent:

```javascript
Type.Named('Either', {Left: {a}, Right: {b}})
```

```javascript
Type.Named('Either', {Right: {b}, Left: {a}})
```

If we're to rely on order I think we should use a data structure which is clearly ordered:

```javascript
Type.Named('Either', [['Left', {a}], ['Right', {b}]])
```

**Comment by JAForbes** [comment]
Okay, good point.  I'd rather not worth with tuples though, I'm hopeful to one day have typescript/flow to know the names of the generated constructors based on the object that is passed in at initialization.  But perhaps we could have an explicit parameter for type variables (and their order).

```js
Type.Named( 'Either', [a,b], {
  Left: { a }
  ,Right { b } 
})
```

I'm thinking of removing `Type.Anonymous` and `Type.Class`, but at the same time adding the documentation and package links.

So I guess we end up with a lot of parameters post 1.0

```js
const Either = 
  Type( 
    'my-package/Either'
    , 'https://github.com/my-package/either#usage'
    , {}
    , [ a, b ]
    , { Left: { a }
      , Right: { b }
      }
  )
```

It's pretty noisy, but should make for far better error messages.  In any case, I'd prefer either an explicit arg for type variable order, or instead rely on alphabetical order as you suggested earlier.

I like the idea of order of appearance, but I take your point that its equally surprising for key order to result in a different type.

**Comment by JAForbes** [comment]
All FL / sanctuary integration I think will live in a superset of this library.  This library is now just focused on the most basic barebones usage.  But it is designed to be extensible via traits:

https://github.com/JAForbes/sum-type/blob/main/docs/spec.md#what-is-a-trait
