### ISSUE TITLE
Remove placeholder?

### ISSUE THREAD

**Issue by JAForbes** [JAForbes/sum-type#13]
Placeholder is convenient, but it's also risky ~~in a dynamic typed language~~.

If I have a type with 3 cases, I might have some code that uses the placeholder and in this case, it happens to be safe, because all other cases happen to have the same structure.

```js
const X = T.Named('X', {
  a: { value: $String }
  ,b: { value: $Number } 
  ,c: { value: $Number }
})

const num = 
  X.case({
    a: value => parseInt(value)
    _: Just
  })
```

In this case, at the time of writing, the `_` will handle all other cases, and because they are of type number, we assume its ok to write `Just`.

But what happens if we add a new case to `X`

```js
const X = T.Named('X', {
  a: { value: $String }
  ,b: { value: $Number } 
  ,c: { value: $Number }
  ,d: { value: $String }
})
```

Now that placeholder will fail.  In this case, sanctuary will tell us there's a problem.   But often, case functions aren't type checked and this leads to brittle code.

I think it'd be better to just not have placeholders at all.

I'm not sold on this, but I've run into this problem several times now, and I really question if its worth the risk.

**Comment by davidchambers** [comment]
`_` leads to problems in Haskell too.

**Comment by JAForbes** [comment]
Interesting, what sort of issues crop up in Haskell?

**Comment by davidchambers** [comment]
I found a bug in some Haskell code recently. The code looked something like this:

```haskell
case x of
  Foo A -> ...
  Foo B -> ...
  Foo C -> ...
  Bar [] -> ...
  Bar xs -> ...
  _ -> error "Cannot handle Baz value"
```

`x` is a member of a type with three data constructors: `Foo`, `Bar`, and `Baz`. At the time this code was written, `Foo A`, `Foo B`, and `Foo C` were the only possible Foo values, so `_` matched only Baz values. Later, though, a new Foo value was defined. The `_` prevented the compiler from giving us an exhaustivity warning, so we forgot to add a case for `Foo D`.

**Comment by JAForbes** [comment]
I've found I can can get around the missing placeholder without repeating logic, by relying on `Maybe`.  So whenever this change is made, that should probably be in the docs.

```
const User = T.Named('X', {
  Id: { user_id: $UUID }
  ,Loaded: { user_id: $UUID, user_name: $.String } 
  ,New: { user_name: $.String }
})

// this works a lot better if the case returns the whole object instead of a spread of args
// User -> Maybe String
const user_name = 
  map( User.case({
    Id: K(Nothing)
    ,Loaded: Just
    ,New: Just
  }, prop('user_name') )

user_name( User.Id(someId) ) 
//=> Nothing

user_name( User.LoadedOf({ user_name: 'Billy' , user_id: someId }) )
//=> Just('Billy')

user_name( User.New({ user_name: 'Billy' }) )
//=> Just('Billy')
```

I like this because you're force to handle every case and actually consider each case, but you're not repeating logic.  In this case, you could just use `S.get`, but often that's not semantic enough, and often the logic is a lot more complicated (like rendering a similar hyperscript view for 2 cases that have similar properties, and a default view for the other cases).

**Comment by JAForbes** [comment]
For reference the upcoming v1 has `otherwise` which is like `_` without the drawbacks as you need to explicitly define the tags it operates on.

https://github.com/JAForbes/sum-type/blob/main/docs/otherwise.md
