### ISSUE TITLE
Named + Docs only.  No Type.Class, or Type.Anonymous.

### ISSUE THREAD

**Issue by JAForbes** [JAForbes/sum-type#14]
Related #10 

Having to provide a name and a documentation link seems verbose and unnecessary, but being forced to makes the library so much more informative when a type error occurs.  If someone really doesn't want to have to do this, they can just pass empty strings in for both arguments.  But I'm strongly leaning towards having this enforced in the default interface.

**Comment by davidchambers** [comment]
Furthermore, if I define

```haskell
data Foo a = Bar a | Baz a | Quux
```

I would like `S.type(Foo.Bar(42))` to give something like `'my-package/Foo'`.

**Comment by JAForbes** [comment]
I'm surprised that already doesn't work.

**Comment by davidchambers** [comment]
You're currently defining `@@type` on the instance, but [sanctuary-type-identifiers][1] requires it on the type representative (this is a change from the way `S.type` worked initially).


[1]: https://github.com/sanctuary-js/sanctuary-type-identifiers
