### ISSUE TITLE
Sanctuary type errors on calling Setup

### ISSUE THREAD

**Issue by hbel** [JAForbes/sum-type#29]
I am experiencing some problems in setting um sum-type for usage. Using what I assume to be the recommended way of initialization:

```
import S from 'sanctuary-def';
import Setup from 'sum-type';

const Type = Setup(S,{checkTypes: true, env: S.env})
```

I only get the following errors from sanctuary-def.

> TypeError: ‘def’ applied to the wrong number of arguments def :: String -> StrMap (Array TypeClass) -> NonEmpty (Array Type) -> Function -> Function ^^^^^^ 1 Expected one argument but received four arguments: - "UnionType.Named" - {} - [String, (StrMap Any), Any] - function CreateUnionType(typeName, rawCases, prototype={}){ ...

I can circumvent these errors by setting _checkTypes_ to false, but this still will leave me with an erroneous _Type_ function that doesn't work.

The package versions I used are: 
sum-type 0.12.0, 
sanctuary-def 0.16.0

**Comment by davidchambers** [comment]
There were breaking changes in [`sanctuary-def@0.15.0`][1]. Until this library is updated you'll need to use an older version of sanctuary-def.


[1]: https://github.com/sanctuary-js/sanctuary-def/releases/tag/v0.15.0

**Comment by arsdragonfly** [comment]
any updates?

**Comment by JAForbes** [comment]
Closing this as v1 is imminent.  But sanctuary-def is no longer supported out of the box, instead this library is focused on simply representing sum-type structures and ensuring they are serializable as JSON.  This is after a lot of dogfooding and usage in frontend state management and sending types over the wire.  

Also I'm not sure peer dependencies managed by different contributors was ever a good pattern in the first place.

However!  There is a traits system which should make it possible for anyone to extend or integrate with more robust algebraic types.

Not exactly sure when this will publish under tag latest.  But the main branch uses the new code, and you can use it via `npm install sum-type@next`.

Very sorry for the long wait.  I wanted to ensure I was solving problems in the real world using this library before making any API decisions.  But I've been using this code for the past 3 years or so in production in varied contexts and I feel like its stable and reliable enough to live at this repository now.
