### ISSUE TITLE
More informative error message when passing in an invalid Type to a Union constructor

### ISSUE THREAD

**Issue by JAForbes** [JAForbes/sum-type#3]
If someone passes in something that doesn't resemble a sanctuary-def type, we should tell them, the key that failed, what probably went wrong and how to fix it.

A classic case could be passing in an unapplied UnaryType instead of a NullaryType, the library will just see it as a function and won't know what to do with it.

**Comment by davidchambers** [comment]
sanctuary-js/sanctuary-def#125 may be relevant here.

**Comment by JAForbes** [comment]
Thanks.  Handled in v1
